/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: 'class',
    content: ['./index.html', './privacy-policy.html', './js/**/*.js'],
    theme: {
        extend: {
            colors: {
                surface: '#0c0c1f',
                'inverse-primary': '#8534c4',
                error: '#ff6e84',
                'on-secondary': '#0b5800',
                'surface-container-high': '#1d1d36',
                'on-secondary-fixed-variant': '#0d6200',
                'surface-container-lowest': '#000000',
                'surface-variant': '#23233f',
                'on-surface-variant': '#aaa8c2',
                'on-tertiary-fixed-variant': '#760037',
                'primary-container': '#c782ff',
                'error-dim': '#d73357',
                'on-error': '#490013',
                'on-secondary-fixed': '#064200',
                'surface-container': '#17172e',
                'secondary-container': '#106e00',
                'primary-dim': '#c57eff',
                'surface-container-highest': '#23233f',
                'on-primary-container': '#38005e',
                'secondary-fixed-dim': '#2be800',
                'surface-container-low': '#111126',
                background: '#0c0c1f',
                'primary-fixed': '#c782ff',
                'inverse-on-surface': '#545369',
                outline: '#74738b',
                'surface-tint': '#d095ff',
                'on-tertiary-container': '#000000',
                'on-primary': '#490078',
                'tertiary-fixed-dim': '#ff75a0',
                'primary-fixed-dim': '#bd6efe',
                'outline-variant': '#46465c',
                'tertiary-fixed': '#ff8eae',
                'on-background': '#e5e3fe',
                'on-error-container': '#ffb2b9',
                secondary: '#2ff801',
                'secondary-dim': '#2be800',
                'surface-dim': '#0c0c1f',
                'surface-bright': '#292947',
                'on-tertiary-fixed': '#380017',
                tertiary: '#ff6b9b',
                'tertiary-dim': '#e30071',
                'on-surface': '#e5e3fe',
                'error-container': '#a70138',
                primary: '#d095ff',
                'on-primary-fixed': '#000000',
                'on-primary-fixed-variant': '#450073',
                'on-secondary-container': '#e7ffd9',
                'on-tertiary': '#47001f',
                'inverse-surface': '#fcf8ff',
                'tertiary-container': '#ff067f',
            },
            fontFamily: {
                headline: ['Plus Jakarta Sans', 'sans-serif'],
                body: ['Manrope', 'sans-serif'],
                label: ['Manrope', 'sans-serif'],
            },
        },
    },
    plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};
